server:
  port: 8090

spring:
  application:
    name: Spring Boot Admin Web
  boot:
    admin:
      url: http://localhost:${server.port}
  jackson:
    serialization:
      indent_output: true

endpoints:
  health:
    sensitive: false