server:
  port: 8082

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#数据库配置
spring:
  datasource:
    dbType: mysql
#    dbType: oracle
#    dbType: db2
    mysql:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/grg_framework?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
    oracle:
      driverClassName: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@10.10.1.183:1521:orcl
      username: facer
      password: facer
    db2:
      driverClassName: com.ibm.db2.jcc.DB2Driver
      url: jdbc:db2://10.10.1.183:50000/biometri
      username: db2admin
      password: db2admin

  boot:
    admin:
      url: http://localhost:8090

management:
  security:
    enabled: false

# mybatis配置
mybatis:
    # 批量插入或更新时，每次事务执行的插入或更新数据行数
#  writeMapperLocations: classpath:mapper/write/**.xml
#  readMapperLocations: classpath:mapper/read/**.xml
  config: mybatis-config.xml
  rows_per_transaction: 500

# Log 配置 级别大写 TRACE|DEBUG|INFO|WARN|ERROR
logging:
  level:
    #root: INFO
    com.grgbanking.biometrics: DEBUG

bd:
  face:
    restapi:
      groupId: grgbanking
      # 百度人脸认证（我司人脸识别）时，一个用户下面挂多张照片的时候会生效，返回多个结果
      topNum: 1
      # 人脸识别阀值
#      threshold: 80
      # 人脸注册
      register: http://face.baidu.com/face_act/facetest/vis-faceverify/v2/faceverify/user/add
      # 人脸更新
      update: http://face.baidu.com/face_act/facetest/vis-faceverify/v2/faceverify/user/update
      # 人脸删除
      delete: http://face.baidu.com/face_act/facetest/vis-faceverify/v2/faceverify/user/delete
      # 用户信息查询
      get: http://face.baidu.com/face_act/facetest/vis-faceverify/v2/faceverify/user/get
      # 说明：人脸认证与人脸识别的差别在于：人脸识别需要指定一个待查找的人脸库中的组；
      # 而人脸认证需要指定具体的用户id即可，不需要指定具体的人脸库中的组；实际应用中，
      # 人脸认证需要用户或系统先输入id，这增加了验证安全度，但也增加了复杂度，具体使用
      # 哪个接口需要视您的业务场景判断。
      # 认证
      verify: http://face.baidu.com/face_act/facetest/vis-faceverify/v2/faceverify/user/verify
      # 识别 1：N
      identify: http://face.baidu.com/face_act/facetest/vis-faceverify/v2/faceverify/user/identify
      # 两两比对
      match: http://face.baidu.com/face_act/facetest/vis-faceverify/v2/faceverify/match
      # 人脸检测
      detect: http://face.baidu.com/face_act/facetest/vis-faceverify/v2/faceverify/detect

