server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  # 关闭自我保护，及时剔除无用服务
  server:
    enableSelfPreservation: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/